# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# cd /home/dev/searchlock/searchlockBackend 
# git pull 
# podman stop $(podman ps --filter "ancestor=modular/backend" -q) 2>/dev/null
# podman build -t modular/backend . 
# podman run -d -p 5002:5002 modular/backend

name: Master API Node.js CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: self-hosted

    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    # this is for backend
    - run: podman stop $(podman ps --filter "ancestor=localhost/modular/backend:latest" -q) 2> /dev/null || true
    - run: podman build -t modular/backend . 
    - run: podman run -d -p 5002:5002 modular/backend

